### ISSUE TITLE
Hierarchy buttons

### ISSUE THREAD

**Issue by Stefan-Espant** [DphnZwp/lets-jam-webapplicatie#14]
Zorg voor een primaire & secundaire stijl om de gebruiker duidelijk te maken welke optie belangrijker is.

<img width="413" alt="Schermafbeelding 2023-01-13 om 11 14 41" src="https://user-images.githubusercontent.com/89298385/212295368-254b2470-7651-4603-9368-4827280ab5c9.png">

**Comment by DphnZwp** [comment]
Was nog niet af in mijn code. In mijn ontwerp is de tweede knop blauw.
