### ISSUE TITLE
overflow

### ISSUE THREAD

**Issue by FouadTaissate** [DphnZwp/lets-jam-webapplicatie#16]
er zit een overflow op de website waardoor je opzij moet scrollen/slepen zodat je de rest van de website kan zien
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/112860051/212295427-d4be812b-3eb2-4bdd-874f-94b817fd3975.png">

**Comment by DphnZwp** [comment]
Opgelost ik heb de afbeelding 100% width gemaakt, zodat hij nu wel op alle schermen responsive is.
