### ISSUE TITLE
Is dit een article of een section, beiden lijkt overdreven!

### ISSUE THREAD

**Issue by ju5tu5** [DphnZwp/lets-jam-webapplicatie#17]
https://github.com/DphnZwp/lets-jam-webapplicatie/blob/3bcce466a27ba2b9495f3f55cd4a19f0b1a9e606/src/routes/%2Bpage.svelte#L1-L2

**Comment by DphnZwp** [comment]
Opgelost! Het is andersom. Het is een article met twee sections.
